#!/usr/bin/env node
// Copies the extension's model instructions (job-fit-evaluator/prompts.js) into
// Tino Cloud's Edge Functions, as an ES module. The server picks the
// instructions for each request itself, from this copy, so it scores exactly
// like the extension does. Run after editing prompts.js; node tools/test.js
// fails while the copy is out of date.
//
// Usage: node tools/cloud.js
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const SOURCE = path.join(root, "job-fit-evaluator", "prompts.js");
const TARGET = path.join(root, "cloud", "supabase", "functions", "_shared", "prompts.js");

function moduleFrom(source) {
  return (
    "// Generated by tools/cloud.js from job-fit-evaluator/prompts.js. Do not edit:\n" +
    "// edit that file and run node tools/cloud.js.\n\n" +
    source.replace(/\s*$/, "\n") +
    "\nexport { JOB_FIT_PROMPTS };\n"
  );
}

if (require.main === module) {
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, moduleFrom(fs.readFileSync(SOURCE, "utf8")));
  console.log(`wrote ${path.relative(root, TARGET)}`);
}

module.exports = { SOURCE, TARGET, moduleFrom };
